apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-mq-server-cert
spec:
  dnsNames:
    - >- 
      *.itzroks-661002q71v-xu4r9r-6ccd7f378ae819553d37d5f2ee142bd6-0000.sjc04.containers.appdomain.cloud
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-mq-cluster-issuer
  secretName: mq-server-cert
  subject:
    organizations:
    - ibm
